/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Calculator.app.src.test.java.Calculator;

import Calculator.app.src.main.java.Calculator.App;
import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
